export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"

export const GET_MEDICINES = "GETMEDICINES"
export const ADD_MEDICINES = "ADDMEDICINES"
export const UPDATE_MEDICINES = "UPDATEMEDICINES"
export const DELETE_MEDICINES = "DELETEMEDICINES"
export const LOADING_MEDICINES = "LOADINGMEDICINES"
export const ERROR_MEDICINES = "ERRORMEDICINES"