export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"

export const GET_MEDICINES = "GETMEDICINES"
export const LOADING_MEDICINES = "LOADINGMEDICINES"
export const ERROR_MEDICINES = "ERRORMEDICINES"